### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by nyaruru1** [Bzi-Han/AndroidSurfaceImgui#5]
Umm can you add hide record?

**Comment by Bzi-Han** [comment]
You mean screen record?
No that plan, you should look for other project of screen record.

**Comment by Bzi-Han** [comment]
I mean find other projects on GitHub.

It's not a bug, just pass `class AImGui` constructor second parameter `autoUpdateOrientation ` with true.
But there is a real problem is the old `Surface` doesn't destroy, I haven't found a way to destroy it yet.
So, for now you can only use horizontal or vertical screen first.

**Comment by Bzi-Han** [comment]
It's support for now.
